apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
  namespace: togglemaster

data:

  # AWS
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/876908012464/togglemaster-analytics-queue"
  AWS_DYNAMODB_TABLE: "togglemaster-analytics"

  # Banco de dados
  DATABASE_URL: "postgres://admin:admin123@postgres-main:5432/flags_db"

  # Cache
  REDIS_URL: "redis://togglemaster-redis.kiylhd.0001.use1.cache.amazonaws.com:6379"

  # Microsserviços
  AUTH_SERVICE_URL: "http://auth-service:8001"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  EVALUATION_SERVICE_URL: "http://evaluation-service:8004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8005"
