apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secret
  namespace: togglemaster

type: Opaque

stringData:
  DATABASE_USER: admin
  DATABASE_PASSWORD: admin123

  MASTER_KEY: admin-secreto-123

  SERVICE_API_KEY: tm_key_EXEMPLO
