apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster

spec:
  replicas: 1

  selector:
    matchLabels:
      app: evaluation-service

  template:
    metadata:
      labels:
        app: evaluation-service

    spec:
      containers:
      - name: evaluation-service
        image: 876908012464.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8004

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        envFrom:
        - configMapRef:
            name: togglemaster-config
        - secretRef:
            name: togglemaster-secret
