apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-runtime-secrets
  namespace: togglemaster
type: Opaque
stringData:
  AUTH_DATABASE_URL: "REPLACE_WITH_AUTH_RDS_URL"
  FLAG_DATABASE_URL: "REPLACE_WITH_FLAG_RDS_URL"
  TARGETING_DATABASE_URL: "REPLACE_WITH_TARGETING_RDS_URL"
  MASTER_KEY: "REPLACE_WITH_SECURE_RANDOM_VALUE"
  SERVICE_API_KEY: "REPLACE_WITH_SECURE_RANDOM_VALUE"
