name: Build and Push to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'
      - 'flag-service/**'
      - 'targeting-service/**'
      - 'evaluation-service/**'
      - 'analytics-service/**'
      - '.github/workflows/main.yml'

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_PREFIX: togglemaster

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - auth-service
          - flag-service
          - targeting-service
          - evaluation-service
          - analytics-service

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build da imagem
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_PREFIX }}/${{ matrix.service }}:latest \
            ./${{ matrix.service }}

      - name: Push da imagem
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_PREFIX }}/${{ matrix.service }}:latest
